// Auto-generated by Portal CMS — do not edit.
// Browser/Vite-friendly version: uses JSON imports instead of readFileSync.
//
// In your vite/vitepress config, add:
//   resolve: { alias: { '#cms': resolve(__dirname, '../../.cms/export/index.client.ts') } }

import _devday2026sJson from './devday2026.json'

// ── Shared types ──────────────────────────────────────────────────────────

/** CMS media file reference */
export interface CmsMedia {
  id: string;
  name: string;
  url: string;
  mime: string;
  size: number;
  width?: number;
  height?: number;
}

// ── Content types ─────────────────────────────────────────────────────────

export interface Devday2026 {
  id: number;
  documentId: string;
  floor?: {
    title?: string;
    id?: string;
    description?: string[];
    card_list?: {
      title?: string;
      description?: string[];
      address?: string;
      time?: string;
      label?: string;
      url?: string;
      bg_light?: CmsMedia;
      bg_dark?: CmsMedia;
      img?: CmsMedia;
    }[];
    agenda?: {
      date?: string;
      content?: {
        time?: string;
        title?: string;
        name?: string;
        post?: string;
      }[];
    }[];
    links?: {
      label?: string;
      url?: string;
    }[];
  };
  createdAt: string;
  updatedAt: string;
  publishedAt: string | null;
  locale: string;
}

/** All published Developer Day 2026 entries */
export const devday2026s: Devday2026[] = (_devday2026sJson as { data: Devday2026[] }).data
