// Auto-generated by Portal CMS — do not edit.
//
// One-time setup: extend this config in your project's tsconfig.json:
//   { "extends": "./.cms/export/tsconfig.json" }
//
// Then import CMS data from anywhere in your project:
//   import { articles }      from '#cms'
//   import type { Article } from '#cms'

import { readFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dir =
  typeof __dirname !== 'undefined'
    ? __dirname
    : dirname(fileURLToPath(import.meta.url))

function _load<T>(slug: string): T[] {
  try {
    const raw = readFileSync(join(__dir, `${slug}.json`), 'utf-8')
    return (JSON.parse(raw) as { data: T[] }).data
  } catch {
    return []
  }
}

function _loadSingleton<T>(slug: string): T | null {
  try {
    const raw = readFileSync(join(__dir, `${slug}.json`), 'utf-8')
    return (JSON.parse(raw) as { data: T }).data ?? null
  } catch {
    return null
  }
}

// ── Shared types ──────────────────────────────────────────────────────────

/** CMS media file reference */
export interface CmsMedia {
  id: string;
  name: string;
  url: string;
  mime: string;
  size: number;
  width?: number;
  height?: number;
}

// ── Content types ─────────────────────────────────────────────────────────

export interface Devday2026 {
  id: number;
  documentId: string;
  floor?: {
    title?: string;
    id?: string;
    description?: string[];
    card_list?: {
      title?: string;
      description?: string[];
      address?: string;
      time?: string;
      label?: string;
      url?: string;
      bg_light?: CmsMedia;
      bg_dark?: CmsMedia;
      img?: CmsMedia;
    }[];
    agenda?: {
      date?: string;
      content?: {
        time?: string;
        title?: string;
        name?: string;
        post?: string;
      }[];
    }[];
    links?: {
      label?: string;
      url?: string;
    }[];
  };
  createdAt: string;
  updatedAt: string;
  publishedAt: string | null;
  locale: string;
}

/** All published Developer Day 2026 entries */
export const devday2026s: Devday2026[] = _load<Devday2026>('devday2026')
